[tool.poetry]
name = "quantflow"
version = "0.1.0"
description = "quantitative analysis"
authors = ["Luca <luca@quantmind.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "^1.22.3"
scipy = "^1.10.1"
pandas = "^2.0.1"
aiohttp = {version = "^3.8.1", optional = true}

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest-cov = "^4.0.0"
mypy = "^1.3.0"
ghp-import = "^2.0.2"
ruff = "^0.0.269"

[tool.poetry.extras]
data = ["aiohttp"]

[tool.poetry.group.book]
optional = true

[tool.poetry.group.book.dependencies]
jupyter-book = "^0.13.1"
nbconvert = "^6.4.5"
jupytext = "^1.13.8"
plotly = "^5.7.0"
ipython = "^8.7.0"
jsonschema = "<4.0"
jupyterlab = "^3.5.2"
jupyter-server = "<2.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
