[tool.poetry]
name = "quantflow"
version = "0.1.0"
description = "quantitative analysis"
authors = ["Luca <luca@quantmind.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.8,<3.11"
numpy = "^1.22.3"
scipy = "^1.8.0"
pandas = "^1.4.2"
jupyterlab = {version = "^3.3.2", optional = true}
jupyter-book = {version = "^0.12.3", optional = true}
nbconvert = {version = "^6.4.5", optional = true}
jupytext = {version = "^1.13.8", optional = true}
plotly = {version = "^5.7.0", optional = true}
aiohttp = {version = "^3.8.1", optional = true}

[tool.poetry.dev-dependencies]
pytest = "black"
black = "^22.3.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
flake8-blind-except = "^0.2.1"
flake8-builtins = "^1.5.3"
flake8-commas = "^2.1.0"
pytest-cov = "^3.0.0"
mypy = "^0.942"
ghp-import = "^2.0.2"

[tool.poetry.extras]
data = ["aiohttp"]
notebook = [
    "jupyterlab",
    "jupyter-book",
    "nbconvert",
    "jupytext",
    "plotly"
]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
