[tool.poetry]
name = "quantflow"
version = "0.1.0"
description = "quantitative analysis"
authors = ["Luca <luca@quantmind.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.10,<4"
numpy = "^1.22.3"
scipy = "^1.8.0"
pandas = "^1.4.2"
aiohttp = {version = "^3.8.1", optional = true}

[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
flake8 = "^6.0.0"
isort = "^5.10.1"
flake8-blind-except = "^0.2.1"
flake8-builtins = "^2.1.0"
pytest-cov = "^4.0.0"
mypy = "^0.991"
ghp-import = "^2.0.2"

[tool.poetry.extras]
data = ["aiohttp"]

[tool.poetry.group.book]
optional = true

[tool.poetry.group.book.dependencies]
jupyterlab = "^3.3.2"
jupyter-book = "^0.12.3"
nbconvert = "^6.4.5"
jupytext = "^1.13.8"
plotly = "^5.7.0"
ipython = "^8.7.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
